In [2]:
count = 0
n_sum = 0

while True:
    number = int(input())
    
    if number == 0:
        break
    
    n_sum += number
    count += 1

if count == 0:
    avg = 0 
else:
    avg =n_sum / count

avg=float(avg)
n_sum=float(n_sum)
print(f"Average and Sum of the above numbers are: {avg} {n_sum}")

Average and Sum of the above numbers are: 14.333333333333334 43.0


In [3]:
x1 = float(input())
y1 = float(input())

x2 = float(input())
y2 = float(input())

midpoint_x = (x1 + x2) / 2
midpoint_y = (y1 + y2) / 2

print("Midpoint:",(x1+x2)/2,(y1+y2)/2)

Midpoint: 3.0 3.0


In [6]:
n=input()
print(n)
type(n)

hi


str

In [8]:
lst=eval(input())
print(type(lst))
print(lst)

<class 'list'>
[1, 2, 3, 4]


In [4]:
lst=[22,2,3,4,5,6,7,8,9]  # append even number in even_num list===> rec function
even_num=[]
for i in range(len(lst)):
    def eve_n(n):
        if:       # base case ?
            pass
        elif n%2==0:
            even_num.append(n)
        eve_n(lst[i])
print(even_num)

[]


In [10]:
def find_longest_word(words_list):
    word_len = []
    for n in words_list:
        #word_len.append((len(n), n))
        word_len.append(len(n))         # it will find the length of each word and append it to word_len variable
        #word_len.sort()
        #return word_len[-1][0], word_len[-1][1]
    
    return max(word_len),word_list[word_len.index(max(word_len))]  # print lenght of longest word first and then here i am finding max number from word_len and then fining
    #it's index and it's index will be same as original list words_list and then getting the value by []

word_list = list(input().split(' ')) # here as you are spliting withi space so my input is like ==> alma better

print(find_longest_word(word_list))

(6, 'better')


In [1]:
def find_longest_word(words_list):
    word_len = []
    for n in words_list:
        #word_len.append((len(n), n))
        word_len.append(len(n))         # it will find the length of each word and append it to word_len variable
        #word_len.sort()
        #return word_len[-1][0], word_len[-1][1]
    
    return max(word_len),word_list[word_len.index(min(word_len))]  # print lenght of longest word first and then here i am finding max number from word_len and then fining
    #it's index and it's index will be same as original list words_list and then getting the value by []

word_list = list(input().split(' ')) # here as you are spliting withi space so my input is like ==> alma better ok

print(find_longest_word(word_list))

(6, 'ok')


In [5]:
def longest_word(word_list):
    word_len=[]
    for i in word_list:
        word_len.append( len(i))
    return max(word_len),word_list[word_len.index(max(word_len))]
word_list=list(input().split(" "))
print(longest_word(word_list))

(6, 'better')


In [ ]:
word_list = ['moiiuuuuuuuuuj','tripathi']
word_len = []
for n in word_list:
    word_len.append(len(n))
print(word_list[word_len.index(max(word_len))])

In [6]:
def longest_word(word_list):
    word_len=[]
    for i in word_list:
        word_len.append( len(i))
    return max(word_len),word_list[word_len.index(min(word_len))]
word_list=list(input().split(" "))
print(longest_word(word_list))

(6, 'ok')


In [1]:
data={'product':['aa','bb'],'Sales':[100,90]}

In [2]:
data

{'product': ['aa', 'bb'], 'Sales': [100, 90]}

In [8]:
# append even number in even_num list===> rec function
even_num=[]
arr=[22,2,3,4,5,6,7,8,9] 
even_num=[]


def eve_n(arr,index):

    if index==len(arr)-1:
        return 
    elif arr%2==0:
        even_num.append(arr)
    eve_n(arr,index+1)

eve_n(arr,index=0)    
print(even_num)


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
# try to append only even numbes from this given list [11,22,12,3] in a new list(even_num=[]), and print it using rec function


1
2
3


n=3

3-3-1

In [10]:
3-(3-1)

1

In [ ]:
n-(n-1)

In [12]:
def ass(n):
    if n>=0:
        return
    else:
        print(n-(n-1))
        ass(n)

ass(3)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


RecursionError: maximum recursion depth exceeded while calling a Python object

In [13]:
def even_numbers(lst, index, even_num):
    if index >= len(lst):
        return

    elif lst[index] % 2 == 0:
        even_num.append(lst[index])

    even_numbers(lst, index + 1, even_num)

lst = [11, 22, 12, 3]
even_num = []
even_numbers(lst, 0, even_num)
print(even_num)


[22, 12]


In [25]:
def print_positives(n,start=0):
  if start > n:
    return
  else:
    print(start)
print_positives(n, start + 1)
n=3
print_positives(n)

NameError: name 'n' is not defined

In [22]:
0

1

In [32]:
def print_positives(n, start=1):
    if start > n:
        return
    print(start,end=", ")
    print_positives(n, start= + 1)

n = 3
print_positives(n)


1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

RecursionError: maximum recursion depth exceeded while calling a Python object

In [34]:
def print_positives(n, start=1):
    if start > n:
        return
    print(start)
    print_positives(n, start + 1)

n = 3
print_positives(n)


1
2
3


factorial(n):


if n==0 or n==1:
retun 1

else:

result=n*fact(n-1)
retun result

In [8]:
def n_factorial(n):
    if n==0 or n==1: # base condition
        return 1
    
    else:
        return n * n_factorial(n-1)   # recursive call with (n-1) parameter.
    
n=int(input("Enter your number: "))
result=n_factorial(n)
print(f"factorial of {n} is {result}")

factorial of 5 is 120


In [30]:
import numpy as np
import pandas as pd

data=pd.read_csv('imdb_data.csv')
data.columns


Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [3]:
data['revenue'].tail(1)

2999    82087155
Name: revenue, dtype: int64

In [15]:
data[['revenue']].iloc[-1]

revenue    82087155
Name: 2999, dtype: int64

In [25]:
data.iloc[:,1]

0       [{'id': 313576, 'name': 'Hot Tub Time Machine ...
1       [{'id': 107674, 'name': 'The Princess Diaries ...
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...                        
2995                                                  NaN
2996                                                  NaN
2997                                                  NaN
2998                                                  NaN
2999                                                  NaN
Name: belongs_to_collection, Length: 3000, dtype: object

In [29]:
data['belongs_to_collection'][data['runtime'].max()]   revenue

"[{'id': 110177, 'name': 'Goal! Collection', 'poster_path': '/jaUSrep1RTzr73QPN3DNkW4LiRn.jpg', 'backdrop_path': '/mKTYkGMseCEFXuZ4CjuZ00xXRCd.jpg'}]"

In [70]:
data['revenue'].max()

1519557910

In [72]:
data['belongs_to_collection'][data['revenue'].idxmax()]

"[{'id': 86311, 'name': 'The Avengers Collection', 'poster_path': '/qJawKUQcIBha507UahUlX0keOT7.jpg', 'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'}]"

In [58]:
import pandas as pd

# Assuming 'data' is your DataFrame
max_revenue_index = data['revenue'].idxmax()

max_revenue_index


1126

In [62]:
import pandas as pd

# Assuming 'data' is your DataFrame
max_revenue_index = data['revenue'].idxmax()

# Extract the 'movie name' where 'revenue' is maximum
movie_with_max_revenue = data.loc[max_revenue_index, 'belongs_to_collection']

# Now 'movie_with_max_revenue' contains the movie name with the maximum revenue
print(movie_with_max_revenue)


[{'id': 86311, 'name': 'The Avengers Collection', 'poster_path': '/qJawKUQcIBha507UahUlX0keOT7.jpg', 'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'}]


In [73]:
data.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   
4                                NaN  tt1380152                ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
4       2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   
4  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  
3  [{'credit_id': '52fe48779251

In [54]:
grades={'Alice':85, 'Bob':92, 'Charlie':88 ,'David':95,'Emily':78,'Frank':91}
# get names grades > 90
std_names=list(grades.keys())
for i in grades.values():
    if i>90:
        print(i)
        print(list(grades.keys())[i])
        

92


IndexError: list index out of range

In [52]:
grades={'Alice':85, 'Bob':92, 'Charlie':88 ,'David':95,'Emily':78,'Frank':91}
print(grades(2))

TypeError: 'dict' object is not callable

In [32]:
'''

Write a Python program to find a string consisting of space-separated characters with given counts.

Example 1:
Input:
{"f": 1, "o": 2}

Output:
f o o

'''

data=eval(input())
new_str=[]
for key,value in data.items():
    new_str.append(key*value)
    new_str=list(''.join(new_str))

result_str=' '.join(new_str)
print(result_str)



f f f o o


"['f', 'o', 'o']"

In [18]:
original_list = ['f', 'o', 'o']

result_string = ' '.join(original_list)

print(result_string)


hi


In [1]:
original_list = ['f', 'oo']

result_list = list(''.join(original_list))

print(result_list)


['f', 'o', 'o']


In [53]:
'''Write a Python program to find the indices of the closest pair from a list of numbers.

Example 1:
Input:
[1, 7, 9, 2, 10]

Output:
[0, 3]'''

data=eval(input())
closest_pair=sorted(data)[:2]
pair_index=[]

for i in closest_pair:
    pair_index.append(data.index(i))
print(pair_index)

[0, 3]


In [46]:
data

[1, 7, 9, 2, 10]

[1, 3, 2]
None


In [3]:
data={'product':['aaa','bbb'],'sales':[100,200]}

In [4]:
data

{'product': ['aaa', 'bbb'], 'sales': [100, 200]}

In [11]:
data.get('sales')

[100, 200]

In [19]:
import numpy as np
arr=np.random.randint(0,255,(4,6))
print(arr)

lst=['l1','l2','l3','l4']
l=list(zip(lst,arr))

arr_2d=np.asarray(l)
print(arr_2d)

[[193 156 186  22 214 247]
 [ 18  93 119 120  26   5]
 [169  77 218 164  20 105]
 [124 175  82  66 247  89]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4, 2) + inhomogeneous part.

In [20]:
import numpy as np

arr = np.random.randint(0, 255, (4, 6))
print(arr)
print(type(arr))
lst = ['l1', 'l2', 'l3', 'l4']
arr_2d = np.column_stack((np.array(lst), arr))
print(arr_2d)


[[161  38 146  66 203  65]
 [102 105 193 153   0 221]
 [245 131 156  30   2  58]
 [120 122  50 148 249 185]]
<class 'numpy.ndarray'>
[['l1' '161' '38' '146' '66' '203' '65']
 ['l2' '102' '105' '193' '153' '0' '221']
 ['l3' '245' '131' '156' '30' '2' '58']
 ['l4' '120' '122' '50' '148' '249' '185']]


In [12]:
no_list=[5551234567,8789546666]
updated=[]
for no in no_list:
    no=str(no)
    updated.append(no[:3]+'-'+no[3:6]+'-'+no[6:]) # or you can take seperator in input() and pass inside for loop like . or /

print(updated)

import pandas as pd

data=pd.DataFrame(updated,columns=['updated_phn_no'])
data

['555-123-4567', '878-954-6666']


updated_phn_no
0   555-123-4567
1   878-954-6666

In [49]:
lst = ['555-123-4567', '(555) 555-5555', '5551234567', '555.555.5555']   
formatted_numbers = []

for item in lst:
    formatted_number = ''.join(char for char in item if char.isdigit())  # loop iniside loop to get number
    formatted_numbers.append(formatted_number)
output = ",".join(formatted_numbers)

print(output)
print('*'*25)

lst=['555-123-4567','(555) 555-5555','5551234567','555.555.5555']
import pandas as pd
data=pd.DataFrame(lst,columns=['raw_phn_no'])
print(data)
print('*'*25)

def get_res(item):
    formatted_number = ''.join(char for char in item if char.isdigit())    # same code as above
    return formatted_number

data['updated_no'] = data['raw_phn_no'].apply(get_res)    # new col using .apply()
data

5551234567,5555555555,5551234567,5555555555
*************************
       raw_phn_no
0    555-123-4567
1  (555) 555-5555
2      5551234567
3    555.555.5555
*************************


raw_phn_no  updated_no
0    555-123-4567  5551234567
1  (555) 555-5555  5555555555
2      5551234567  5551234567
3    555.555.5555  5555555555

In [33]:
lst = ['555-123-4567', '(555) 555-5555', '5551234567', '555.555.5555']
formatted_numbers = []

for item in lst:
    formatted_number = ''.join(char for char in item if char.isdigit())

    formatted_numbers.append(formatted_number)

output = ",".join(formatted_numbers)

print(output)



5551234567,5555555555,5551234567,5555555555


In [38]:
def get_res(item):
    formatted_number = ''.join(char for char in item if char.isdigit())
    return formatted_number

In [40]:
data['updated_no'] = data['raw_phn_no'].apply(get_res)

In [41]:
data

raw_phn_no  updated_no
0    555-123-4567  5551234567
1  (555) 555-5555  5555555555
2      5551234567  5551234567
3    555.555.5555  5555555555




# Apply the function to the 'raw_phn_no' column


print(data)


In [1]:
'5'*5

'55555'

In [3]:
'5'^2

TypeError: unsupported operand type(s) for ^: 'str' and 'int'

In [5]:
!pip install joblib

Defaulting to user installation because normal site-packages is not writeable


In [15]:
from joblib import Memory
mem=Memory(location='cache')
@mem.cache
def cal_mean(num):
    print('calculating mean')
    total=sum(num)
    return(total/len(num))

my_list=[1,2,3,4,5,6,7,18,9,10]
result1=cal_mean(my_list)
print(result1)

6.5


In [14]:
print(dir(Memory))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cache', 'clear', 'debug', 'eval', 'format', 'reduce_size', 'warn']


In [9]:
l='abcdefghijklmnopqrstuvwxyz'
my_str="The quick brown fox jumps over the lazy dog"
out=[]
for ele_of_l in l:

    if ele_of_l in my_str:
        out.append("True")
    else:
        out.append("False")

if "False" in out:
    print(False)
else:
    print(True)        
    

True


26


['True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True']
